title: Ng Thanh Dam # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a 3rd-year student in AI at FPT University. 
  <br><br>
  I am interested in machine learning, deep learning as computer vision and natural language processing.
  <br><br>
  <a href="https://www.linkedin.com/in/nguyen-thanh-dam-808661216/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
